### ISSUE TITLE
Simple GUI for the simplekey?

### ISSUE THREAD

**Issue by dashohoxha** [nyarly/simplekey#14]
This is a nice and simple GUI tool that maybe can be adopted for this project: https://github.com/guelfoweb/easygpg

However I am not sure whether adding a simple GUI is within the scope and boundaries of this project.

**Comment by nyarly** [comment]
I think the two projects are related - if easygpg wanted to include UI items for simplekey, that'd be cool, or if a third project wanted to wrap simplekey, also cool. Adding more deps than gpg and the shell is definitely counter to the simplekey project goals, though.

**Comment by dashohoxha** [comment]
You are right. This project is related too: https://github.com/dashohoxha/egpg
Actually it is a fork and extension of simplekey (it supports some more commands, beyond the very basic ones). So, I am closing this issue in favor of this one: https://github.com/dashohoxha/egpg/issues/12
