### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dashohoxha** [nyarly/simplekey#15]
Is it possible to take this project and redistribute it with a different license (either modified or unmodified)? Does the current license allow it?

**Comment by strugee** [comment]
http://choosealicense.com/licenses/unlicense/

Or you could, you know. Read the license. It's dead-simple and will take you under a minute.

**Comment by nyarly** [comment]
The above is substantially correct. I would prefer that if you were going to fork the project you use a substantially different name, but it's all in the public domain, so redistribute as you see fit.

The intention from day one is that it all be simple enough that a user could review it themselves to see if they like it, or modify to make it more their own.

**Comment by dashohoxha** [comment]
Thanks. I will try to think of a different name.
